# Generated by Django 4.1.1 on 2022-10-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber_cad', models.CharField(db_column='NAMBER_CARD', max_length=16)),
                ('cvc2', models.CharField(db_column='CVC2', max_length=4)),
                ('date_vale', models.DateField(auto_now_add=True, db_column='DATE_VALE')),
                ('type_card', models.CharField(choices=[('GL', 'GOLD'), ('FR', 'FREE'), ('BL', 'BLACK'), ('PR', 'PREMIUM'), ('GO', 'GOOD')], db_column='TYPE_CARD', max_length=2)),
                ('flag', models.CharField(choices=[('MT', 'MASTERCAD'), ('VI', 'VISA'), ('EL', 'ELO')], db_column='FLAG', max_length=2)),
                ('nfc', models.BooleanField(db_column='NFC', default=True)),
                ('blocked', models.BooleanField(db_column='BLOCKED', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('sex', models.CharField(choices=[('m', 'MASCULINO'), ('f', 'FEMININO')], db_column='SEX', max_length=1)),
                ('birthdate', models.DateField(db_column='BIRTHDATE')),
                ('status', models.CharField(choices=[('n', 'NORMAL'), ('m', 'MEDIO'), ('b', 'BAIXO')], db_column='STATUS', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(db_column='AGENCY', default='0001', max_length=4)),
                ('account', models.CharField(db_column='ACCOUNT', max_length=6)),
                ('balance', models.DecimalField(db_column='BALANCE', decimal_places=2, default=0.0, max_digits=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velue', models.DecimalField(db_column='VALUE', decimal_places=2, default=0.0, max_digits=30)),
                ('date_contract', models.DateField(auto_now_add=True, db_column='DATE_VALE')),
                ('installments', models.IntegerField(db_column='INSTALLMENTS')),
                ('installments_paind', models.IntegerField(db_column='INSTALLMENTS_PAIND')),
                ('fees', models.DecimalField(db_column='FEES', decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('A', 'APROVADO'), ('R', 'REPROVADO')], db_column='STATUS', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='back_end/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(db_column='CPF', max_length=11)),
                ('password', models.CharField(db_column='PASSWORD', max_length=8)),
                ('token', models.CharField(db_column='Token', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tranferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_movement', models.DateField(auto_now_add=True, db_column='DATE_MOVEMENTE')),
                ('type', models.CharField(choices=[('P', 'PIX'), ('T', 'TRANSFER')], db_column='TYPE', max_length=1)),
                ('value', models.DecimalField(db_column='VALUE', decimal_places=2, default=0.0, max_digits=30)),
                ('credited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credited', to='back_end.conta')),
                ('debited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debited', to='back_end.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento_Emprstimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_pay', models.DecimalField(db_column='AMOUNT_TO_PAY', decimal_places=2, default=0.0, max_digits=30)),
                ('date_pay', models.DateField(auto_now_add=True, db_column='DATE_PAY')),
                ('expiration_date', models.DateField(auto_now_add=True, db_column='EXPIRATION_DATE')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.emprestimos')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(db_column='INVOICE_AMOUNT', decimal_places=2, default=0.0, max_digits=30)),
                ('expiration_date', models.DateField(auto_now_add=True, db_column='EXPIRATION_DATE')),
                ('fees', models.DecimalField(db_column='FEES', decimal_places=2, default=0.0, max_digits=10)),
                ('cartoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_column='DATE')),
                ('value', models.DecimalField(db_column='VALUE', decimal_places=2, max_digits=10)),
                ('time', models.TimeField(auto_now_add=True, db_column='TIME')),
                ('type', models.CharField(choices=[('P', 'PIX'), ('T', 'TRANSFER'), ('D', 'DEPOSIT'), ('W', 'WAGE'), ('AP', 'ACCOUNT_PAYMENT'), ('PA', 'PAYMENT'), ('RE', 'REVERSAL')], db_column='TYPE', max_length=2)),
                ('conclusion', models.CharField(choices=[('SU', 'SUCCESS'), ('FL', 'FAILED')], db_column='CONCLUSION', max_length=2)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(db_column='ROAD', max_length=5)),
                ('number', models.CharField(db_column='NUMBER', max_length=5)),
                ('cep', models.CharField(db_column='CEP', max_length=8)),
                ('city', models.CharField(db_column='CITY', max_length=255)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], db_column='STATE', max_length=2)),
                ('district', models.CharField(db_column='DISTRICT', max_length=255)),
                ('complement', models.CharField(db_column='COMPLEMENTE', max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_column='TELEPHONE', max_length=11)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.usuario'),
        ),
        migrations.AddField(
            model_name='cartoes',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.conta'),
        ),
    ]
